/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const customermessages_Logic_PreprocessMessages = require('./code/customermessages-logic-preprocessMessages');

class akhilasiripurapu_1_d02Srv extends LCAPApplicationService {
    async init() {

        this.before('READ', 'CustomerMessages', async (request) => {
            await customermessages_Logic_PreprocessMessages(request);
        });

        return super.init();
    }
}


module.exports = {
    akhilasiripurapu_1_d02Srv
};